[tool.isort]
profile = "black"
force_single_line = true
add_imports = "from __future__ import annotations"

[tool.ruff]
fix = true

[tool.ruff.lint]
select = [
    "A",
    "ANN",
    "ARG",
    "B",
    "BLE",
    "COM",
    "C4",
    "C90",
    "D",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "EXE",
    "F",
#    "FBT",
    "G",
    "I",
    "ICN",
    "INP",
    "ISC",
    "N",
    "NPY",
    "PD",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "TCH",
    "TID",
    "TRY",
    "T10",
    "T20",
    "W",
]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D107",
    "D205",
    "D203",
    "D213",
    "ERA001",
    "PLR2004",
]


[tool.ruff.lint.per-file-ignores]
"*/tests/*.py" = ["S101"]
"advent_of_code_2021/day16/main.py" = ["PLR0911"]
"advent_of_code_2022/day11/main.py" = ["C901"]
"advent_of_code_2022/day13/main.py" = ["PGH001", "PLW2901", "S307"]
"advent_of_code_2022/day14/main.py" = ["C901", "PLR0912"]


[tool.ruff.lint.isort]
force-single-line = true
